# Generated by Django 5.2.8 on 2025-11-19 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherquery',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запрос погоды', 'verbose_name_plural': 'Запросы погоды'},
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='country',
            field=models.CharField(blank=True, max_length=20, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость ветра'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание погоды'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='from_cache',
            field=models.BooleanField(default=False, verbose_name='Из кэша'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='temperature',
            field=models.FloatField(verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время запроса'),
        ),
        migrations.AlterField(
            model_name='weatherquery',
            name='unit',
            field=models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', max_length=1, verbose_name='Единицы измерения'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['city'], name='weather_app_city_937f05_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherquery',
            index=models.Index(fields=['timestamp'], name='weather_app_timesta_c5a98c_idx'),
        ),
    ]
